const copy: Record<string, [string, string]> = {
  ex_faster_speed: ['Faster speed', 'Schnellere Geschwindigkeit'],
  ex_fast_badge: ['Fast', 'Schnell'],
  ex_fast_cost: ['Higher usage or cost. Account availability applies.', 'Höherer Verbrauch oder Kosten. Je nach Konto verfügbar.'],
  ex_fast_unavailable: ['Not supported by the selected model.', 'Für das gewählte Modell nicht unterstützt.'],
  ex_nav: ['Execution', 'Ausführung'],
  ex_tasks: ['TASKS', 'AUFGABEN'],
  ex_task: ['Task', 'Aufgabe'],
  ex_new_task: ['New task', 'Neue Aufgabe'],
  ex_search: ['Find a task…', 'Aufgabe suchen …'],
  ex_sidebar_note: ['Your agents. One workspace.', 'Ihre Agenten. Ein Arbeitsbereich.'],
  ex_workspace: ['AGENT WORKSPACE', 'AGENTEN-ARBEITSBEREICH'],
  ex_heading: ['Give your ideas a team.', 'Ein Team für Ihre Ideen.'],
  ex_subheading: ['Follow the work, from the first instruction to the final handoff.', 'Verfolgen Sie die Arbeit vom ersten Auftrag bis zur Übergabe.'],
  ex_demo: ['Explore a sample', 'Beispiel ansehen'],
  ex_no_workspace: ['No workspace selected', 'Kein Arbeitsbereich gewählt'],
  ex_connecting: ['Connecting…', 'Verbindung wird hergestellt …'],
  ex_preview_notice: ['Sample workflow · illustrative data, no agents are executing.', 'Beispiel-Workflow · Illustrative Daten, es laufen keine Agenten.'],
  ex_back_live: ['Back to live', 'Zur Live-Ansicht'],
  ex_approval_needed: ['This run needs your approval.', 'Dieser Lauf benötigt Ihre Genehmigung.'],
  ex_new_instruction: ['NEW INSTRUCTION', 'NEUER AUFTRAG'],
  ex_bounded: ['Bounded execution', 'Ausführung mit Limits'],
  ex_prompt_label: ['Describe your task', 'Aufgabe beschreiben'],
  ex_prompt_placeholder: ['Describe a task or queue your next change…', 'Aufgabe beschreiben oder nächste Änderung einreihen …'],
  ex_attach: ['Attach text context', 'Textdatei anhängen'],
  ex_select_model: ['Select a model', 'Modell auswählen'],
  ex_auto_help: ['Manual requests approval before running; Auto follows repository policy.', 'Manuell fordert vor dem Start eine Genehmigung an; Auto folgt der Repository-Richtlinie.'],
  ex_manual: ['Manual', 'Manuell'],
  ex_auto: ['Auto', 'Auto'],
  ex_queue: ['Queue task', 'Aufgabe einreihen'],
  ex_settings: ['Workspace & run limits', 'Arbeitsbereich & Ausführungslimits'],
  ex_policy_note: ['Execution respects workspace permissions, approval gates and budgets.', 'Arbeitsbereichsrechte, Genehmigungen und Budgets gelten für jeden Lauf.'],
  ex_manage_workflows: ['Configure multi-agent workflows', 'Multi-Agenten-Workflows konfigurieren'],
  ex_toggle_task: ['Expand or collapse task', 'Aufgabe ein- oder ausklappen'],
  ex_no_matches: ['No matching tasks.', 'Keine passenden Aufgaben.'],
  ex_no_tasks: ['Your tasks will appear here.', 'Hier erscheinen Ihre Aufgaben.'],
  ex_empty_title: ['Your next task starts here.', 'Hier beginnt Ihre nächste Aufgabe.'],
  ex_empty_body: ['Choose a model and workspace, then describe an outcome. Each execution step will appear here as it happens.', 'Wählen Sie Modell und Arbeitsbereich und beschreiben Sie das Ziel. Jeder Ausführungsschritt erscheint hier mit seinem aktuellen Stand.'],
  ex_agents: ['Agents', 'Agenten'],
  ex_iterations: ['Iterations', 'Iterationen'],
  ex_running: ['running', 'läuft'],
  ex_done: ['done', 'fertig'],
  ex_failed: ['failed', 'fehlgeschlagen'],
  ex_pending: ['pending', 'ausstehend'],
  ex_actions: ['steps started', 'Schritte gestartet'],
  ex_execution_trace: ['Execution trace', 'Ausführungsverlauf'],
  ex_response_received: ['Response received', 'Antwort empfangen'],
  ex_depends_on: ['Depends on', 'Abhängig von'],
  ex_waiting_start: ['Waiting for the first step to start.', 'Der erste Schritt ist noch nicht gestartet.'],
  ex_stop: ['Stop run', 'Lauf stoppen'],
  ex_sample: ['Sample', 'Beispiel'],
  ex_recorded: ['Recorded execution', 'Aufgezeichnete Ausführung'],
  ex_output: ['Output', 'Ausgabe'],
  ex_provider_output: ['Model response', 'Modellantwort'],
  ex_responses: ['responses', 'Antworten'],
  ex_summary_only: ['Only the execution summary was retained for this run.', 'Für diesen Lauf wurde nur die Zusammenfassung aufbewahrt.'],
  ex_awaiting_output: ['The agent is working. Its response will appear here when available.', 'Der Agent arbeitet. Seine Antwort erscheint hier, sobald sie vorliegt.'],
  ex_no_output: ['No output recorded.', 'Keine Ausgabe aufgezeichnet.'],
  ex_live: ['Live', 'Live'],
  ex_disconnected: ['Connection interrupted', 'Verbindung unterbrochen'],
  ex_need_prompt_model: ['Describe a task and select a model first.', 'Beschreiben Sie eine Aufgabe und wählen Sie ein Modell.'],
  ex_context_too_large: ['The attached context exceeds the input limit.', 'Der angehängte Kontext überschreitet das Eingabelimit.'],
  ex_remove_file: ['Remove attachment', 'Anhang entfernen'],
  ex_file_limits: ['Attach up to five text files, each at most 100 KB (.txt, .md, .json, .csv, .log).', 'Bis zu fünf Textdateien mit je maximal 100 KB anhängen (.txt, .md, .json, .csv, .log).'],
  ex_automations: ['Automations', 'Automationen'],
  ex_marketplace: ['Agents & skills', 'Agenten & Skills'],
  ex_group: ['Group', 'Gruppe'],
  ex_all_tasks: ['All tasks', 'Alle Aufgaben'],
  ex_active_tasks: ['Active', 'Aktiv'],
  ex_pinned: ['Pinned', 'Angeheftet'],
  ex_sort: ['Sort', 'Sortierung'],
  ex_newest: ['Newest', 'Neueste'],
  ex_oldest: ['Oldest', 'Älteste'],
  ex_project: ['Project', 'Projekt'],
  ex_all_projects: ['All projects', 'Alle Projekte'],
  ex_scope: ['Permission scope', 'Berechtigungsumfang'],
  ex_scope_plan: ['Plan', 'Planen'],
  ex_scope_agent: ['Workspace write', 'Dateien ändern'],
  ex_scope_chat: ['Read only', 'Nur lesen'],
  ex_effort: ['Reasoning effort', 'Denkaufwand'],
  ex_effort_default: ['Default', 'Standard'],
  ex_plan: ['Execution plan', 'Ausführungsplan'],
  ex_toggle_plan: ['Expand or collapse plan', 'Plan ein- oder ausklappen'],
  ex_pause_updates: ['Pause updates', 'Anzeige pausieren'],
  ex_plan_note: ['Progress comes from recorded workflow steps. Pausing updates keeps agents running.', 'Der Fortschritt zeigt aufgezeichnete Workflow-Schritte. Beim Pausieren der Anzeige laufen Agenten weiter.'],
  ex_now: ['now', 'jetzt'],
  ex_pin: ['Pin task', 'Aufgabe anheften'],
  ex_unpin: ['Unpin task', 'Aufgabe lösen'],
  ex_plan_empty: ['A clear path to the outcome.', 'Schritt für Schritt zum Ziel.'],
  ex_progress: ['Progress', 'Fortschritt'],
  ex_copy_command: ['Copy command', 'Befehl kopieren'],
  ex_combined_output: ['Combined output', 'Kombinierte Ausgabe'],
  ex_stderr_unavailable: ['This provider reports combined output only.', 'Dieser Provider liefert nur eine kombinierte Ausgabe.'],
  ex_activity_feed: ['COMMAND ACTIVITY', 'BEFEHLSAKTIVITÄT'],
  ex_execution_duration: ['Execution duration', 'Ausführungsdauer'],
  ex_duration_note: ['Measured from recorded step start and completion.', 'Aus aufgezeichnetem Start und Abschluss des Schritts berechnet.'],
  ex_no_commands: ['No structured terminal events were reported for this step.', 'Für diesen Schritt liegen keine strukturierten Terminal-Ereignisse vor.'],
  ex_resume_updates: ['Resume updates', 'Anzeige fortsetzen'],
  ex_updates_paused: ['Updates paused', 'Anzeige pausiert'],
  ex_copied: ['Copied', 'Kopiert'],
  ex_copy_failed: ['Clipboard access failed. Select and copy the command from its expanded output.', 'Zugriff auf die Zwischenablage fehlgeschlagen. Kopieren Sie den Befehl aus der aufgeklappten Ausgabe.'],
};

export const EXECUTION_COPY = {
  en: Object.fromEntries(Object.entries(copy).map(([key, values]) => [key, values[0]])),
  de: Object.fromEntries(Object.entries(copy).map(([key, values]) => [key, values[1]])),
};
