const copy: Record<string, [string, string]> = {
  ra_nav: ['Repository analytics', 'Repository-Analyse'],
  ra_eyebrow: ['REPOSITORY INTELLIGENCE', 'REPOSITORY-ANALYSE'],
  ra_heading: ['Repository analytics', 'Repository-Analyse'],
  ra_previous: ['Previous snapshot', 'Vorheriger Snapshot'], ra_next: ['Next snapshot', 'Nächster Snapshot'], ra_pin_action: ['Pin snapshot', 'Snapshot anheften'],
  ra_subheading: ['Production, tests, and the history that connects them.', 'Produktionscode, Tests und ihre Entwicklung.'],
  ra_repo: ['Repository', 'Repository'], ra_branch: ['Branch', 'Branch'],
  ra_snapshot: ['Snapshot', 'Snapshot'], ra_days: ['days of inspected history', 'Tage untersuchte Historie'],
  ra_day_preset: ['{days} days', '{days} Tage'], ra_all: ['All time', 'Gesamte Zeit'],
  ra_range: ['Date range', 'Zeitraum'], ra_metric: ['Line metric', 'Zeilenmetrik'],
  ra_nonblank: ['Nonblank LOC', 'LOC ohne Leerzeilen'], ra_total: ['Total LOC', 'LOC gesamt'],
  ra_export: ['Export CSV', 'CSV exportieren'], ra_refresh: ['Refresh', 'Aktualisieren'],
  ra_production: ['Production LOC', 'Produktions-LOC'], ra_tests: ['Test LOC', 'Test-LOC'],
  ra_ratio: ['Test / production ratio', 'Test-/Produktionsverhältnis'], ra_net: ['Net change', 'Nettoänderung'],
  ra_files: ['{count} counted files', '{count} gezählte Dateien'], ra_since: ['since selected start', 'seit Beginn der Auswahl'],
  ra_ratio_note: ['Code volume, not a quality score.', 'Codeumfang, keine Qualitätsbewertung.'],
  ra_series: ['Code over time', 'Code im Zeitverlauf'],
  ra_prod_short: ['Production', 'Produktion'], ra_test_short: ['Tests', 'Tests'],
  ra_hover: ['Hover to inspect', 'Bewegen zum Prüfen'], ra_pin: ['Click to pin', 'Klicken zum Anheften'],
  ra_keyboard: ['Arrow keys to inspect · Enter to pin · Escape to release', 'Pfeiltasten zum Prüfen · Enter zum Anheften · Escape zum Lösen'],
  ra_pinned: ['Snapshot pinned', 'Snapshot angeheftet'], ra_unpin: ['Release snapshot', 'Snapshot lösen'],
  ra_start: ['History start', 'Beginn der Historie'], ra_end: ['History end', 'Ende der Historie'],
  ra_brush: ['Scrub repository history', 'Repository-Historie eingrenzen'],
  ra_movement: ['Changes', 'Änderungen'],
  ra_movement_note: ['Each bar compares recorded snapshots; gaps may span several days.', 'Jeder Balken vergleicht erfasste Snapshots; Abstände können mehrere Tage umfassen.'],
  ra_distribution: ['Where the lines live', 'Wo der Code liegt'],
  ra_directory: ['Directory', 'Verzeichnis'], ra_table: ['Inspect snapshot data', 'Snapshot-Daten ansehen'],
  ra_date: ['Date (UTC)', 'Datum (UTC)'], ra_commit: ['Commit', 'Commit'],
  ra_coverage: ['{snapshots} snapshots · {commits} first-parent commits inspected', '{snapshots} Snapshots · {commits} First-Parent-Commits untersucht'],
  ra_sampled: ['Sampled history', 'Historie in Stichproben'],
  ra_truncated: ['History is limited to the latest {limit} first-parent commits. All time means the inspected history.', 'Die Historie umfasst maximal die letzten {limit} First-Parent-Commits. Gesamte Zeit bezeichnet die untersuchte Historie.'],
  ra_scope: ['Committed source files only. Comments count as lines. Non-source files, vendor/build/fixture paths, binaries, symlinks and uncommitted changes are excluded.', 'Nur eingecheckte Quelldateien. Kommentare zählen als Zeilen. Andere Dateitypen, Vendor-/Build-/Fixture-Pfade, Binärdateien, Symlinks und nicht eingecheckte Änderungen sind ausgeschlossen.'],
  ra_test_rule: ['Tests are classified by test/spec file names and test, spec, e2e, Cypress or Playwright directories.', 'Tests werden anhand von Test-/Spec-Dateinamen und Test-, Spec-, E2E-, Cypress- oder Playwright-Verzeichnissen zugeordnet.'],
  ra_partial: ['Partial scan: {files} files skipped in the selected snapshot; {snapshots} snapshots unavailable. Counts are lower bounds; growth is hidden when a selected snapshot is incomplete.', 'Teilweise erfasst: {files} Dateien im gewählten Snapshot ausgelassen; {snapshots} Snapshots nicht verfügbar. Werte sind Untergrenzen; Wachstum bleibt bei unvollständigen gewählten Snapshots ausgeblendet.'],
  ra_partial_short: ['Incomplete source coverage', 'Quelldateien unvollständig erfasst'],
  ra_method: ['Details & method', 'Details & Messmethode'],
  ra_loading: ['Reading repository snapshots…', 'Repository-Snapshots werden gelesen …'],
  ra_loading_note: ['The first scan can take a few seconds. Results are cached for two minutes.', 'Die erste Erfassung kann einige Sekunden dauern. Ergebnisse werden zwei Minuten zwischengespeichert.'],
  ra_no_repos: ['Register a repository to explore its history.', 'Registrieren Sie ein Repository, um seine Historie zu erkunden.'],
  ra_empty: ['This repository has no commits yet.', 'Dieses Repository hat noch keine Commits.'],
  ra_error: ['Repository analytics could not be loaded. Check that the registered repository is available and Git is installed.', 'Die Repository-Analyse konnte nicht geladen werden. Prüfen Sie, ob das registrierte Repository verfügbar und Git installiert ist.'],
  ra_invalid_branch: ['This local branch is unavailable. Select another branch or refresh.', 'Dieser lokale Branch ist nicht verfügbar. Wählen Sie einen anderen Branch oder aktualisieren Sie die Ansicht.'],
  ra_scan_limit: ['The scan reached its resource limit. Try again after the current scan finishes or choose a smaller repository.', 'Die Erfassung hat ihr Ressourcenlimit erreicht. Versuchen Sie es nach Abschluss der laufenden Erfassung erneut oder wählen Sie ein kleineres Repository.'],
  ra_no_range: ['No recorded snapshot falls within this range.', 'In diesem Zeitraum liegt kein erfasster Snapshot.'],
  ra_one: ['One snapshot available. A second snapshot is needed to measure change.', 'Ein Snapshot verfügbar. Für eine Änderung wird ein zweiter Snapshot benötigt.'],
  ra_no_source: ['No matching source files in this snapshot.', 'Keine passenden Quelldateien in diesem Snapshot.'],
  ra_other: ['Other directories', 'Weitere Verzeichnisse'],
  ra_cached: ['Read at {time} · cached up to 2 minutes', 'Erfasst um {time} · bis zu 2 Minuten zwischengespeichert'],
};

export const REPOSITORY_ANALYTICS_COPY = {
  en: Object.fromEntries(Object.entries(copy).map(([key, values]) => [key, values[0]])),
  de: Object.fromEntries(Object.entries(copy).map(([key, values]) => [key, values[1]])),
};
